services:
  - type: web
    name: network-simulator
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8080
      - key: API_PORT
        value: 8081
      - key: DJANGO_PORT
        value: 8083
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_RELAY_URL
        sync: false

