-- Migration 020: Add submission_id to timer_sessions for idempotent submissions
-- Each practice session gets a unique submission_id generated by the client.
-- ON CONFLICT (submission_id) prevents double-click / network retry duplicates.

ALTER TABLE timer_sessions
    ADD COLUMN IF NOT EXISTS submission_id VARCHAR(64) DEFAULT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_timer_sessions_submission_id
    ON timer_sessions (submission_id)
    WHERE submission_id IS NOT NULL;
