ServerName localhost
ServerTokens Prod

<VirtualHost *:{{PORT}}>
    DocumentRoot /app

    <Directory /app>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        AcceptPathInfo On
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 common
</VirtualHost>
