'use strict';'require view';'require dom';'require poll';'require fs';'require ui';'require uci';'require form';'require network';'require firewall';'require tools.widgets as widgets';'require tools.network as nettools';return view.extend({load:function(){return Promise.all([uci.load('network'),uci.load('firewall')])},render:function(){var m=new form.Map('network',_('WAN Settings'),_('This page provides the function of WAN connection parameter(s) configuration.'));var s=m.section(form.NamedSection,'wan','interface');s.addremove=false;function displayOnlyValue(field,title,placeholder,defval){var opt=s.option(form.Value,'_'+field,_(title));opt.placeholder=placeholder;opt.default=defval;opt.readonly=true;opt.modalonly=true;opt.cfgvalue=function(){return defval;};}
displayOnlyValue('connectname','Connection Name','WAN','WAN');displayOnlyValue('type','Type','','Routing');o=s.option(form.Value,'mtu',_('MTU'));o.default=1492;o.datatype='range(128,1500)';var proto=uci.get('network','wan','proto')||'pppoe';if(proto==='pppoe'){displayOnlyValue('linktype','Link Type','','PPP');displayOnlyValue('ppptarnstype','PPP Transfer Type','','PPPoE');var pppLabel=s.option(form.DummyValue,'ppplabel','<strong>PPP</strong>');pppLabel.modalonly=true;pppLabel.cfgvalue=function(section_id){return'<strong>PPP</strong>';};pppLabel.render=function(){var div=E('div',{'class':'cbi-value'},[E('label',{'class':'cbi-section-node','style':'background-color: #f0f0f0; padding: 10px;'},this.cfgvalue())]);return div;};var o=s.option(form.Value,'username',_('Username'),_('Please enter a value with 1 ~ 64 characters.'));o.optional=false;o.rmempty=false;o.modalonly=true;o.validate=function(section_id,value){if(value.length<1||value.length>64)
return _('Username must be between 1 and 64 characters.');return true;};o=s.option(form.Value,'password',_('Password'),_('Please enter a value with 1 ~ 64 characters.'));o.optional=false;o.rmempty=false;o.password=true;o.modalonly=true;o.validate=function(section_id,value){if(value.length<1||value.length>64)
return _('Password must be between 1 and 64 characters.');return true;};displayOnlyValue('authentype','Authentication Type','','Auto');displayOnlyValue('connectmode','Connection Mode','','Always On');}
else if(proto==='dhcp'){displayOnlyValue('linktype','Link Type','','IP');}
var ipversion=uci.get('network','wan','ipv6')||'ipv4';if(ipversion=="1")
{displayOnlyValue('ipversion','IP Version','','IPv4/IPv6');}
else
{displayOnlyValue('ipversion','IP Version','','IPv4');}
if(proto==='dhcp'){var ipv4Label=s.option(form.DummyValue,'ipv4label','<strong>IPv4</strong>');ipv4Label.modalonly=true;ipv4Label.cfgvalue=function(section_id){return'<strong>IPv4</strong>';};ipv4Label.render=function(){var div=E('div',{'class':'cbi-value'},[E('label',{'class':'cbi-section-node','style':'background-color: #f0f0f0; padding: 10px;'},this.cfgvalue())]);return div;};displayOnlyValue('iptype','IP Type','','DHCP');}
o=s.option(form.ListValue,'nat',_('NAT'));o.widget='radio';o.value('1',_('On'));o.value('0',_('Off'));o.default=uci.get('firewall','wanzone','masq')||'1';o.modalonly=true;o.cfgvalue=function(){return uci.get('firewall','wanzone','masq')||'1';};if(ipversion=="1"){var ipv6Label=s.option(form.DummyValue,'ipv6label','<strong>IPv6</strong>');ipv6Label.modalonly=true;ipv6Label.cfgvalue=function(section_id){return'<strong>IPv6</strong>';};ipv6Label.render=function(){var div=E('div',{'class':'cbi-value'},[E('label',{'class':'cbi-section-node','style':'background-color: #f0f0f0; padding: 10px;'},this.cfgvalue())]);return div;};displayOnlyValue('v6acquiremode','IPv6 Info Acquire Mode','','Auto');o=s.option(form.ListValue,'requestPD',_('Request PD'));o.widget='radio';o.value('1',_('On'));o.value('0',_('Off'));o.default='1';o.readonly=true;var guaAllowedFrom=s.option(form.DummyValue,'guaallowedfrom',_('GUA Allowed From'));guaAllowedFrom.modalonly=true;guaAllowedFrom.cfgvalue=function(section_id){return _('GUA Allowed From');};guaAllowedFrom.render=function(){var div=E('div',{'class':'cbi-value'},[E('label',{'class':'cbi-section-node'},this.cfgvalue())]);return div;};var slaacFlag=s.option(form.Flag,'slaac',_('SLAAC'));slaacFlag.modalonly=true;slaacFlag.rmempty=false;slaacFlag.default='0';slaacFlag.title='';slaacFlag.render=function(){var input=E('input',{type:'checkbox',name:this.config+'.'+this.section+'.'+this.option,id:this.cbid,value:'1',checked:'checked',disabled:true});var label=E('label',{for:this.cbid,style:'margin-left: 10px;'},_('SLAAC'));var div=E('div',{'class':'cbi-value'},[E('div',{'class':'cbi-value-field','style':'margin-left:180px;'},[input,label])]);return div;};var dhcpv6Flag=s.option(form.Flag,'dhcpv6',_('DHCPv6'));dhcpv6Flag.modalonly=true;dhcpv6Flag.rmempty=false;dhcpv6Flag.default='1';dhcpv6Flag.title='';dhcpv6Flag.render=function(){var reqaddress=uci.get('network','wan6','reqaddress')||'try';var isChecked=(reqaddress==='try');var input=E('input',{type:'checkbox',name:this.cbid,id:this.cbid,value:'1',disabled:true,checked:isChecked?'checked':null});input.addEventListener('click',()=>{this.value=input.checked?'1':'0';});var label=E('label',{for:this.cbid,style:'margin-left: 10px;'},_('DHCPv6'));var div=E('div',{'class':'cbi-value'},[E('div',{'class':'cbi-value-field','style':'margin-left:180px; '},[input,label])]);return div;};}
var device=uci.get('network','wan','device')||'';var vlanMatch=device.match(/^pon0\.(\d+)$/);var initialVlanEnabled=!!vlanMatch;var initialVlanId=vlanMatch?vlanMatch[1]:'';var vlanFlag=s.option(form.ListValue,'vlanenable',_('VLAN'));vlanFlag.widget='radio';vlanFlag.value('1',_('On'));vlanFlag.value('0',_('Off'));vlanFlag.default=initialVlanEnabled?'1':'0';vlanFlag.modalonly=true;vlanFlag.rmempty=false;vlanFlag.enabled='1';vlanFlag.disabled='0';var vlanId=s.option(form.Value,'vlanid',_('VLAN ID'),_('Please enter a value between 1 and 4094.'));vlanId.optional=false;vlanId.datatype='uinteger';vlanId.range=[1,4094];vlanId.modalonly=true;vlanId.depends('vlanenable','1');vlanId.cfgvalue=()=>initialVlanId;vlanId.placeholder=_('Enter VLAN ID (1-4094)');vlanId.validate=function(section_id,value){if(value===''||value<1||value>4094)
return _('VLAN ID must be an integer between 1 and 4094.');return true;};m.save=function(){return Promise.resolve().then(()=>{var username=s.children.find(opt=>opt.option==='username')?.formvalue('wan')||'';var password=s.children.find(opt=>opt.option==='password')?.formvalue('wan')||'';if(proto==='pppoe'&&s.children.some(opt=>opt.option==='username')&&s.children.some(opt=>opt.option==='password')){uci.set('network','wan','username',username);uci.set('network','wan','password',password);}
var mtuValue=s.children.find(opt=>opt.option==='mtu')?.formvalue('wan')||'1492';uci.set('network','wan','mtu',mtuValue);var natValue=s.children.find(opt=>opt.option==='nat')?.formvalue('wan')||'1';uci.set('firewall','wanzone','masq',natValue);var vlanEnabled=vlanFlag.formvalue('wan')==='1';var vlanIdVal=vlanId.formvalue('wan');var newDevice=vlanEnabled&&vlanIdVal?`pon0.${vlanIdVal}`:'pon0';uci.set('network','wan','device',newDevice);var vlanwanExists=uci.sections('network','device').some(dev=>dev['.name']==='vlanwan');if(vlanEnabled&&vlanIdVal){if(!vlanwanExists){uci.add('network','device','vlanwan');}
uci.set('network','vlanwan','type','8021q');uci.set('network','vlanwan','ifname','pon0');uci.set('network','vlanwan','vid',vlanIdVal);uci.set('network','vlanwan','name',newDevice);}else if(vlanwanExists){uci.remove('network','vlanwan');}
return uci.save().then(()=>{return true;});});};return m.render();}});