'use strict';'require view';'require rpc';'require uci';'require form';'require dom';return view.extend({callGetPageLoad:rpc.declare({object:'luci',method:'usecmapi',params:['method','data'],expect:{}}),g_getChannelListFromXMLCache:function(channel_data,countryCodeIN,bandIN,bandWidthIN){var data=JSON.parse(channel_data);for(const entry of data.ChannalData){if(entry.Band===bandIN&&entry.ShortCountryName===countryCodeIN&&entry.Bandwidth===bandWidthIN){return entry.PossibleChannelList.split(',');}}
return[];},load:function(){return Promise.all([this.callGetPageLoad('get_wlan_info','{}'),this.callGetPageLoad('webagent_get_countrychanel','{}')]);},render:function(data){let basicadData=JSON.parse(data[0].data);let m,s,o;m=new form.JSONMap(basicadData,_('WLAN Global Configuration'),_('This page provides the function of WLAN basic parameter(s) configuration.'));const option_names=Object.keys(basicadData.WLANBasicAd);for(let i=0;i<option_names.length;i++){var option_name=option_names[i];var display_name=option_name==="1"?"WLAN (5G)":"WLAN (2.4G)";basicadData.WLANBasicAd[option_name]['Alias']=display_name;var bandIN=option_name==="1"?"5GHz":"2.4GHz";if(basicadData.WLANBasicAd[option_name]['SGI']===true){basicadData.WLANBasicAd[option_name]['SGI']=1;}else{basicadData.WLANBasicAd[option_name]['SGI']=0;}
if(basicadData.WLANBasicAd[option_name]['AutoChannelEnable']===true){basicadData.WLANBasicAd[option_name]['Channel']='Auto';}
basicadData.WLANBasicAd[option_name]['ChannalList']=this.g_getChannelListFromXMLCache(data[1].data,basicadData.WLANBasicAd[option_name]['RegulatoryDomain'],bandIN,basicadData.WLANBasicAd[option_name]['BandWidth']);}
s=m.section(form.GridSection,'WLANBasicAd');s.anonymous=true;o=s.option(form.HiddenValue,'InstID');o.modalonly=true;o=s.option(form.HiddenValue,'AutoChannelEnable');o.modalonly=true;o=s.option(form.Value,'Alias');o.modalonly=false;o=s.option(form.ListValue,'Channel',_('Channel'));o.value('Auto','Auto');let possibleChannels=this.g_getChannelListFromXMLCache(data[1].data,basicadData.WLANBasicAd[1]['RegulatoryDomain'],bandIN,basicadData.WLANBasicAd[1]['BandWidth']);possibleChannels.forEach(function(channel){o.value(channel,channel);});o.rmempty=false;o.editable=true;o.modalonly=true;o=s.option(form.ListValue,'Standard',_('Mode'));o.value('ax','IEEE 802.11ax Only');o.rmempty=false;o.readonly=true;o.modalonly=true;o=s.option(form.ListValue,'RegulatoryDomain',_('Country/Region'));o.value('CNI','China');o.value('AUI','Australia');o.value('BRI','Brazil');o.value('CAI','Canada');o.value('EGI','Egypt');o.value('FRI','France');o.value('DEI','Germany');o.value('GRI','Greece');o.value('HKI','China Hongkong');o.value('ITI','Italy');o.value('KRI','Korea');o.value('ESI','Spain');o.value('GBI','United Kingdom');o.value('USI','United States of America');o.value('VNI','Vietnam');o.rmempty=false;o.editable=true;o.modalonly=true;o.readonly=true;o=s.option(form.ListValue,'BandWidth',_('Band Width'));o.value('Auto','Auto');o.value('20MHz','20MHz');o.value('40MHz','40MHz');o.rmempty=false;o.editable=true;o.modalonly=true;o=s.option(form.Flag,'SGI',_('SGI'));o.modalonly=true;o=s.option(form.Value,'X_ZTE-COM_BeaconPeriod',_('Beacon Interval'));o.modalonly=true;o=s.option(form.ListValue,'TransmitPower',_('Transmitting Power'));o.value(100,'100%');o.value(80,'80%');o.value(60,'60%');o.value(40,'40%');o.value(20,'20%');o.rmempty=false;o.editable=true;o.modalonly=true;const viewInstance=this;s.handleModalSave=function(section_id){const mapNode=this.getActiveModalMap();let activeMap=dom.findClassInstance(mapNode);activeMap.save(null,true);const formData=activeMap.data.data[activeMap.section];if(formData['Channel']==='Auto'){formData['AutoChannelEnable']=true;formData['Channel']=1;}else{formData['AutoChannelEnable']=false;}
if(formData['Channel']&&formData['Channel']!=='Auto'){formData['Channel']=parseInt(formData['Channel']);}
formData['TransmitPower']=parseInt(formData['TransmitPower']);formData['X_ZTE-COM_BeaconPeriod']=parseInt(formData['X_ZTE-COM_BeaconPeriod']);if(formData['SGI']==='1'){formData['SGI']=true;}else{formData['SGI']=false;}
const filteredData=formData;viewInstance.callGetPageLoad('globalconfig_set_wlaninfo',JSON.stringify(filteredData)).then(()=>{window.location.reload();}).catch(err=>{console.error('Save failed:',err);});return false;};return m.render().then(function(el){var g_getChannelListFromXMLCache=function(channel_data,countryCodeIN,bandIN,bandWidthIN)
{var data=JSON.parse(channel_data);for(const entry of data.ChannalData){if(entry.Band===bandIN&&entry.ShortCountryName===countryCodeIN&&entry.Bandwidth===bandWidthIN){return entry.PossibleChannelList.split(',');}}
return[];};const observer=new MutationObserver((mutations)=>{mutations.forEach(mutation=>{if(mutation.addedNodes.length){mutation.addedNodes.forEach(node=>{if(node.classList&&node.classList.contains('button-row')){initModalContent(node);}});}});});observer.observe(document.body,{childList:true,subtree:true});const initModalContent=(modal)=>{const section=modal.closest('.cbi-modal').querySelector('.cbi-section');if(!section)return;const standardSelect=section.querySelector('[data-name="Standard"] select');const channelSelect=section.querySelector('[data-name="Channel"] select');const bandwidthSelect=section.querySelector('[data-name="BandWidth"] select');const CountrySelect=section.querySelector('[data-name="RegulatoryDomain"] select');const instidobj=section.querySelector('[data-name="InstID"] input');if(!standardSelect||!channelSelect||!bandwidthSelect||!CountrySelect||!instidobj){return;}
var instid="";if(instidobj){instid=instidobj.value;}
const SGIDIV=section.querySelector('[data-name="SGI"]');const BandWidthDIV=section.querySelector('[data-name="BandWidth"]');if(instid==='IGD.LD.WLAN1'){standardSelect.innerHTML='';const modes2g=[{value:'b',text:'IEEE 802.11b Only'},{value:'g',text:'IEEE 802.11g Only'},{value:'n',text:'IEEE 802.11n Only'},{value:'b,g',text:'Mixed (802.11b/g)'},{value:'g,n',text:'Mixed (802.11g/n)'},{value:'b,g,n',text:'Mixed (802.11b/g/n)'},{value:'b,g,n,ax',text:'Mixed (802.11b/g/n/ax)'},{value:'ax',text:'IEEE 802.11ax Only'}];modes2g.forEach(mode=>{standardSelect.add(new Option(mode.text,mode.value));});standardSelect.value=basicadData.WLANBasicAd[0]['Standard'];}else if(instid==='IGD.LD.WLAN5'){standardSelect.innerHTML='';const modes5g=[{value:'a',text:'IEEE 802.11a Only'},{value:'n',text:'IEEE 802.11n Only'},{value:'a,n',text:'Mixed (802.11a/n)'},{value:'a,n,ac',text:'Mixed (802.11a/n/ac)'},{value:'ac',text:'IEEE 802.11ac Only'},{value:'a,n,ac,ax',text:'Mixed (802.11a/n/ac/ax)'},{value:'ax',text:'IEEE 802.11ax Only'}];modes5g.forEach(mode=>{standardSelect.add(new Option(mode.text,mode.value));});standardSelect.value=basicadData.WLANBasicAd[1]['Standard'];}
const updateChannels=()=>{const bandWidth=bandwidthSelect.value;const country=CountrySelect.value;const band=instid.includes('WLAN5')?'5GHz':'2.4GHz';const channels=g_getChannelListFromXMLCache(data[1].data,country,band,bandWidth)||[];Array.from(channelSelect.options).forEach(opt=>{if(opt.value!=='Auto')channelSelect.remove(opt.index);});channels.forEach(channel=>{channelSelect.add(new Option(channel,channel));});channelSelect.value='Auto';};let handleStandardChange=()=>{};const bindEvents=()=>{bandwidthSelect.removeEventListener('change',updateChannels);CountrySelect.removeEventListener('change',updateChannels);standardSelect.removeEventListener('change',handleStandardChange);bandwidthSelect.addEventListener('change',updateChannels);CountrySelect.addEventListener('change',updateChannels);if(instid==='IGD.LD.WLAN5'){const allowedBW=['Auto','20MHz','40MHz'];if(['ac','a,n,ac','a,n,ac,ax','ax'].includes(standardSelect.value)){allowedBW.push('80MHz','160MHz');}
if(standardSelect.value==="a"){BandWidthDIV.style.display="none";SGIDIV.style.display="none";}else{BandWidthDIV.style.display="";SGIDIV.style.display="";}
bandwidthSelect.innerHTML='';allowedBW.forEach(bw=>{bandwidthSelect.add(new Option(bw,bw));});bandwidthSelect.value=basicadData.WLANBasicAd[1]['BandWidth'];handleStandardChange=()=>{if(['ac','a,n,ac','a,n,ac,ax','ax'].includes(standardSelect.value)){allowedBW.push('80MHz','160MHz');}
if(standardSelect.value==="a"){BandWidthDIV.style.display="none";SGIDIV.style.display="none";}else{BandWidthDIV.style.display="";SGIDIV.style.display="";}
bandwidthSelect.innerHTML='';allowedBW.forEach(bw=>{bandwidthSelect.add(new Option(bw,bw));});bindEvents();updateChannels();bandwidthSelect.value='Auto';};standardSelect.addEventListener('change',handleStandardChange);}
updateChannels();if(instid==='IGD.LD.WLAN1'){channelSelect.value=basicadData.WLANBasicAd[0]['Channel'];if(standardSelect.value==="b"||standardSelect.value==="g"){BandWidthDIV.style.display="none";SGIDIV.style.display="none";}else{BandWidthDIV.style.display="";SGIDIV.style.display="";}
handleStandardChange=()=>{if(standardSelect.value==="b"||standardSelect.value==="g"){BandWidthDIV.style.display="none";SGIDIV.style.display="none";}else{BandWidthDIV.style.display="";SGIDIV.style.display="";}
bindEvents();updateChannels();};standardSelect.addEventListener('change',handleStandardChange);}else if(instid==='IGD.LD.WLAN5'){channelSelect.value=basicadData.WLANBasicAd[1]['Channel'];}};bindEvents();};return el;});},handleSave:null,handleSaveApply:null,handleSaveInst:null,handleReset:null,});