'use strict';'require view';'require uci';'require form';'require rpc';'require ui';function convertToSeconds(input){if(!input||typeof input!=='string'){return'';}
const match=input.match(/^(\d+)([dhms])?$/);if(!match){return'';}
const value=parseInt(match[1],10);const unit=match[2]||'s';let totalSeconds;switch(unit){case'd':totalSeconds=value*24*60*60;break;case'h':totalSeconds=value*60*60;break;case'm':totalSeconds=value*60;break;case's':totalSeconds=value;break;default:return'';}
return String(totalSeconds);}
return view.extend({callCmapi:rpc.declare({object:'luci',method:'usecmapi',params:['method','data'],expect:{}}),load:function(){return Promise.all([uci.load('dhcp'),uci.load('network')]);},render:function(data){let m,s,o;m=new form.Map('network',_('DHCP Server'),_('DHCP Form Configuration.'));s=m.section(form.NamedSection,'lan',_('DHCP Form'));var Ignore=uci.get('dhcp','lan','ignore')||'0';var ignore=s.option(form.ListValue,'ignore',_('Enable'));ignore.widget='radio';ignore.cfgvalue=()=>Ignore;ignore.value('0',_('On'));ignore.value('1',_('Off'));ignore.datatype='integer';o=s.option(form.Value,'ipaddr',_('LAN IP Address'),_('LAN IP Address'));o.optional=false;o.rmempty=false;o.datatype='ip4addr'
o=s.option(form.Value,'netmask',_('Subnet Mask'));o.datatype='ip4addr'
o.rmempty=false;var ipaddr=uci.get('network','lan','ipaddr')||'';var start=uci.get('dhcp','lan','start')||'';var limit=uci.get('dhcp','lan','limit')||'';var ipMatch=ipaddr.match(/^(\d+\.\d+\.\d+\.)/);var initialStartIP=ipMatch?ipMatch[1]:'';var result=parseInt(start)+parseInt(limit)-1;var StartIPId=s.option(form.Value,'start',_('DHCP Start IP Address'));StartIPId.cfgvalue=()=>initialStartIP+start;StartIPId.rmempty=false;StartIPId.datatype='ip4addr'
var EndIPId=s.option(form.Value,'end',_('DHCP End IP Address'));EndIPId.cfgvalue=()=>initialStartIP+result;EndIPId.rmempty=false;EndIPId.datatype='ip4addr'
var leasetimeId=uci.get('dhcp','lan','leasetime')||'';var LeaseTime=s.option(form.Value,'leasetime',_('Custom Lease Time'),_('Please enter a value between 120(s) and 157680000(s) .'));LeaseTime.cfgvalue=()=>convertToSeconds(leasetimeId);LeaseTime.datatype='range(120,157680000)';var dhcp_option=uci.get('dhcp','lan','dhcp_option')||[];var parts=dhcp_option.length>0?dhcp_option[0].split(','):[];var ip1=parts[1];var ip2=parts[2];var Primary_DNSId=s.option(form.Value,'Primary_DNS',_('Primary DNS'));Primary_DNSId.cfgvalue=()=>ip1||ipaddr;Primary_DNSId.datatype='ip4addr'
var Secondary_DNSId=s.option(form.Value,'Secondary_DNS',_('Secondary DNS'));Secondary_DNSId.cfgvalue=()=>ip2||"0.0.0.0";Secondary_DNSId.datatype='ip4addr'
const viewInstance=this;m.save=function(){var mapNode=s.map.root;const invalidInputs=mapNode.querySelectorAll('input.cbi-input-invalid');if(invalidInputs.length>0){return null;}
return Promise.resolve().then(()=>{var ignore=s.children.find(opt=>opt.option==='ignore')?.formvalue('lan')||'';uci.set('dhcp','lan','ignore',ignore);var ipaddr=s.children.find(opt=>opt.option==='ipaddr')?.formvalue('lan')||'';var netmask=s.children.find(opt=>opt.option==='netmask')?.formvalue('lan')||'';uci.set('network','lan','ipaddr',ipaddr);uci.set('network','lan','netmask',netmask);var StartIPIdVal=StartIPId.formvalue('lan');var EndIPIdVal=EndIPId.formvalue('lan');var leasetimeIdVal=LeaseTime.formvalue('lan');var last=StartIPIdVal.split('.').pop();var lastOctet=EndIPIdVal.split('.').pop();var resultID=parseInt(lastOctet)+1-parseInt(last);uci.set('dhcp','lan','start',last);uci.set('dhcp','lan','limit',resultID);uci.set('dhcp','lan','leasetime',leasetimeIdVal+'s');var Primary_DNSIdVal=Primary_DNSId.formvalue('lan');var Secondary_DNSIdVal=Secondary_DNSId.formvalue('lan');var DNS_value=`6,${Primary_DNSIdVal}${Secondary_DNSIdVal ? `,${Secondary_DNSIdVal}` : ''}`;DNS_value=Secondary_DNSIdVal==="0.0.0.0"?`6,${Primary_DNSIdVal}`:DNS_value;DNS_value=Primary_DNSIdVal?DNS_value:`6,${Secondary_DNSIdVal}`;uci.unset('dhcp','lan','dhcp_option');if(Primary_DNSIdVal!=""||Secondary_DNSIdVal!=""){uci.set('dhcp','lan','dhcp_option',[DNS_value]);}
const result={InstID:`DEV.BRIDGING.BR1`,Enable:ignore==='0'?1:0};return uci.save().then(()=>{return true;}).then(()=>viewInstance.callCmapi('webagent_br_dhcp_enable_set',JSON.stringify(result)))});};return m.render();}});