'use strict';'require view';'require rpc';'require ui';'require uci';'require form';return view.extend({callGetPageLoad:rpc.declare({object:'luci',method:'usecmapi',params:['method','data'],expect:{},}),load:function(){return Promise.all([this.callGetPageLoad('webagent_mesh_get_topodata_info','{}'),this.callGetPageLoad('webagent_mesh_get_1905dev_info','{}'),this.callGetPageLoad('webagent_mesh_get_all_non1905dev_info','{}'),]);},initial_template_svg:function(TOPO_CONTAINER_WIDTH,CONTROLLER_CONTAINER_WIDTH,CONTROLLER_CONTAINER_HEIGHT,AGENT_CONTAINER_WIDTH,AGENT_CONTAINER_HEIGHT,LAYER_AGENT_AXIS_Y,svgHeight,draw,topodata){const self=this;function TopoShowPopData(circleobj,devinfotop){let macvalue=circleobj.getAttribute('id');let parentId={ParentID:macvalue,};self.callGetPageLoad('webagent_mesh_get_non1905dev_info',JSON.stringify(parentId)).then((res)=>{var data=JSON.parse(res.data)||{};console.log('popData->',data);var popupDiv=E('div',{id:'PopDevDataDiv',style:`
                position: absolute;
                top: ${devinfotop}px;
                width: 960px;
                background-color: white;
                border: 1px solid #ddd;
                border-radius: 10px;
                filter: drop-shadow(2px 4px 6px grey);
                padding: 16px;
                z-index: 1000;
            `,});var closeBtn=E('button',{style:`
                position: absolute;
                top: 8px;
                right: 8px;
                background: none;
                border: none;
                cursor: pointer;
                width: 24px;         
                height: 24px;      
                padding: 0;          
                display: flex;       
                justify-content: center;
                align-items: center;
            `,},[E('img',{src:L.resource('icons/close.png'),style:`display: block;`,alt:'Close',click:function(){popupDiv.remove();RestoreCircleColor();if(document.getElementById('polygon')!=null){document.getElementById('polygon').remove();}},}),]);popupDiv.appendChild(closeBtn);var routerTitle=E('h4',{style:`
                margin: 12px 0 5px;
                font-size: 12px;
                color: #18BDF0;
            `,},['Router information']);popupDiv.appendChild(routerTitle);var routerDiv=E('div',{id:'routeinfo',style:`border: 1px solid #ddd; border-radius: 10px; background-color: #f0f2f5;`,});var routerImg=E('img',{style:`
                display: block;
                float:left;
                margin: 10px 70px 10px 10px;
            `,src:L.resource('icons/router_big.png'),});var masterData=data.GetPopData.master;var linktype={connecting:'/','2.4G':'2.4GHz','5G':'5GHz',ETH:'ETH',};var routerTable=E('table',{style:`
                width: 100%;
                display: block;
                margin-bottom: 10px;
            `,},[E('thead',{},[E('tr',{style:'background-color: #f0f2f5;'},[E('th',{style:'padding: 8px; text-align: left; width: 130px;'},['Device']),E('th',{style:'padding: 8px; text-align: left; width: 130px;'},['MAC']),E('th',{style:'padding: 8px; text-align: left; width: 130px;'},['Software Ver']),E('th',{style:'padding: 8px; text-align: left; width: 120px;'},['IP']),E('th',{style:'padding: 8px; text-align: left; width: 50px;'},['Backhaul']),E('th',{style:'padding: 8px; text-align: left; width: 120px'},['Link Speed']),E('th',{style:'padding: 8px; text-align: left; width: 120px'},['Assoc Time']),]),]),E('tbody',{},[E('tr',{style:'background-color: #f0f2f5;'},[E('td',{style:'padding: 8px; width: 130px;'},[masterData.DeviceName||'N/A']),E('td',{style:'padding: 8px; width: 130px;'},[masterData.MacAddr||'N/A']),E('td',{style:'padding: 8px; width: 130px;'},[masterData.SoftwareVer||'N/A']),E('td',{style:'padding: 8px; width: 120px;'},[masterData.IpAddr||'N/A']),E('td',{style:'padding: 8px; width: 50px;'},[linktype[masterData.AccessType]||'N/A']),E('td',{style:'padding: 8px; width: 120px;'},[masterData.LinkSpeed=='0'?'/':masterData.LinkSpeed+'Mbps']),E('td',{style:'padding: 8px; width: 120px;'},[sec2HrMinSec(masterData.AssocTime)]),]),]),]);routerDiv.appendChild(routerImg);routerDiv.appendChild(routerTable);popupDiv.appendChild(routerDiv);var networkTitle=E('h4',{style:`
                margin: 12px 0 5px;
                font-size: 12px;
                color: #18BDF0;
            `,},['Network cable-connected devices']);popupDiv.appendChild(networkTitle);var lanData=data.GetPopData.lan;var lanItems=[];for(var key in lanData){if(key!=='MGET_INST_NUM'&&typeof lanData[key]==='object'){lanItems.push(lanData[key]);}}
var networkTbodyRows=[];if(lanItems.length>0){lanItems.forEach(function(device){networkTbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px;'},[device.HostName||device.MacAddr||'Unknown']),E('td',{style:'padding: 8px;'},[device.MacAddr||'N/A']),E('td',{style:'padding: 8px;'},[device.IpAddr||'N/A']),E('td',{style:'padding: 8px;'},[sec2HrMinSec(device.AssocTime)]),]));});}else{networkTbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px; text-align: left; font-style: italic; color: #999;',colspan:4,},[E('img',{src:L.resource('icons/info_s.png'),style:'width: 16px; height: 16px; margin-right: 8px;',}),'There are no data now.',]),]));}
var networkTable=E('table',{style:`
                width: 100%;
                border: 1px solid #ddd;
                margin-bottom: 16px;
            `,},[E('thead',{},[E('tr',{style:'background-color: #f0f2f5;'},[E('th',{style:'padding: 8px; text-align: left;'},['Device Name']),E('th',{style:'padding: 8px; text-align: left;'},['MAC']),E('th',{style:'padding: 8px; text-align: left;'},['IP']),E('th',{style:'padding: 8px; text-align: left;'},['AP uptime']),]),]),E('tbody',{},networkTbodyRows),]);popupDiv.appendChild(networkTable);var ghz24Title=E('h4',{style:`
                margin: 12px 0 5px;
                font-size: 12px;
                color: #18BDF0;
            `,},['2.4GHz connected devices']);popupDiv.appendChild(ghz24Title);var wlan2GData=data.GetPopData.wlan2G;var ghz24Items=[];for(var key in wlan2GData){if(key!=='MGET_INST_NUM'&&typeof wlan2GData[key]==='object'){ghz24Items.push(wlan2GData[key]);}}
var ghz24TbodyRows=[];if(ghz24Items.length>0){ghz24Items.forEach(function(device){ghz24TbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px;'},[device.HostName||device.MacAddr||'Unknown']),E('td',{style:'padding: 8px;'},[device.MacAddr||'N/A']),E('td',{style:'padding: 8px;'},[device.IpAddr||'N/A']),E('td',{style:'padding: 8px;'},[sec2HrMinSec(device.AssocTime)]),E('td',{style:'padding: 8px;'},[formatRate(device.RxRateBps)]),E('td',{style:'padding: 8px;'},[formatRate(device.TxRateBps)]),E('td',{style:'padding: 8px;'},[device.Btm||'N/A']),E('td',{style:'padding: 8px;'},[(device.Rssi||'N/A')+' dBm']),E('td',{style:'padding: 8px;'},[device.WirelessMode||'N/A']),E('td',{style:'padding: 8px;'},[device.SNR||'N/A']),]));});}else{ghz24TbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px; text-align: left; font-style: italic; color: #999;',colspan:11,},[E('img',{src:L.resource('icons/info_s.png'),style:'width: 16px; height: 16px; margin-right: 8px;',}),'There are no data now.',]),]));}
var ghz24Table=E('table',{style:`
                width: 100%;
                border: 1px solid #ddd;
                margin-bottom: 16px;
            `,},[E('thead',{},[E('tr',{style:'background-color: #f0f2f5;'},[E('th',{style:'padding: 8px; text-align: left;'},['Device Name']),E('th',{style:'padding: 8px; text-align: left;'},['MAC']),E('th',{style:'padding: 8px; text-align: left;'},['IP']),E('th',{style:'padding: 8px; text-align: left;'},['AP uptime']),E('th',{style:'padding: 8px; text-align: left;'},['Downlink']),E('th',{style:'padding: 8px; text-align: left;'},['Uplink']),E('th',{style:'padding: 8px; text-align: left;'},['BTM']),E('th',{style:'padding: 8px; text-align: left;'},['RSSI']),E('th',{style:'padding: 8px; text-align: left;'},['Wireless Mode']),E('th',{style:'padding: 8px; text-align: left;'},['SNR']),]),]),E('tbody',{},ghz24TbodyRows),]);popupDiv.appendChild(ghz24Table);var ghz5Title=E('h4',{style:`
                margin: 12px 0 5px;
                font-size: 12px;
                color: #18BDF0;
            `,},['5GHz connected devices']);popupDiv.appendChild(ghz5Title);var wlan5GData=data.GetPopData.wlan5G;var ghz5Items=[];for(var key in wlan5GData){if(key!=='MGET_INST_NUM'&&typeof wlan5GData[key]==='object'){ghz5Items.push(wlan5GData[key]);}}
var ghz5TbodyRows=[];if(ghz5Items.length>0){ghz5Items.forEach(function(device){ghz5TbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px;'},[device.HostName||device.MacAddr||'Unknown']),E('td',{style:'padding: 8px;'},[device.MacAddr||'N/A']),E('td',{style:'padding: 8px;'},[device.IpAddr||'N/A']),E('td',{style:'padding: 8px;'},[sec2HrMinSec(device.AssocTime)]),E('td',{style:'padding: 8px;'},[formatRate(device.RxRateBps)]),E('td',{style:'padding: 8px;'},[formatRate(device.TxRateBps)]),E('td',{style:'padding: 8px;'},[device.Btm||'N/A']),E('td',{style:'padding: 8px;'},[device.Rrm||'N/A']),E('td',{style:'padding: 8px;'},[(device.Rssi||'N/A')+' dBm']),E('td',{style:'padding: 8px;'},[device.WirelessMode||'N/A']),E('td',{style:'padding: 8px;'},[device.SNR||'N/A']),]));});}else{ghz5TbodyRows.push(E('tr',{},[E('td',{style:'padding: 8px; text-align: left; font-style: italic; color: #999;',colspan:11,},[E('img',{src:L.resource('icons/info_s.png'),style:'width: 16px; height: 16px; margin-right: 8px;',}),'There are no data now.',]),]));}
var ghz5Table=E('table',{style:`
                width: 100%;
                border: 1px solid #ddd;
            `,},[E('thead',{},[E('tr',{style:'background-color: #f0f2f5;'},[E('th',{style:'padding: 8px; text-align: left;'},['Device Name']),E('th',{style:'padding: 8px; text-align: left;'},['MAC']),E('th',{style:'padding: 8px; text-align: left;'},['IP']),E('th',{style:'padding: 8px; text-align: left;'},['AP uptime']),E('th',{style:'padding: 8px; text-align: left;'},['Downlink']),E('th',{style:'padding: 8px; text-align: left;'},['Uplink']),E('th',{style:'padding: 8px; text-align: left;'},['BTM']),E('th',{style:'padding: 8px; text-align: left;'},['RRM']),E('th',{style:'padding: 8px; text-align: left;'},['RSSI']),E('th',{style:'padding: 8px; text-align: left;'},['Wireless Mode']),E('th',{style:'padding: 8px; text-align: left;'},['SNR']),]),]),E('tbody',{},ghz5TbodyRows),]);popupDiv.appendChild(ghz5Table);var topoArea=document.getElementById('svg-area');topoArea.appendChild(popupDiv);function formatRate(bps){if(!bps)return'0 bps';const value=parseInt(bps);if(value>=1000000)return(value/1000000).toFixed(1)+' Mbps';if(value>=1000)return(value/1000).toFixed(1)+' Kbps';return value+' bps';}
function sec2HrMinSec(sec){if(sec==''){return'0s';}
var s,m,h;s=parseInt(sec%60);m=parseInt(sec/60,10)%60;h=parseInt(sec/3600,10);return h+'h'+m+'min'+s+'s';}});}
function RestoreCircleColor(){var circleobj=document.getElementsByTagName('circle');var routernum=circleobj.length;for(var i=0;i<routernum;i++){var singleroute=circleobj[i];if(singleroute.getAttribute('name')=='selectedroute'){singleroute.setAttribute('stroke','#e2e2e8');singleroute.setAttribute('stroke-width','1');singleroute.removeAttribute('name');}}}
function drawDevice(x,y,w,h,devHeight,data,type){var backgdimg='url(#backgroundimg)';if(type=='agent'){backgdimg='url(#agentbackgroundimg)';}
var container=draw.rect(w,h).attr({fill:'#fff','fill-opacity':0.5,stroke:'#000','stroke-width':0.0,}).move(x,y);var devX=x+(w-devHeight)/2;var devCircle=draw.circle(devHeight).attr({id:data.MACAddr,InstID_Dev:data.instID,stroke:'#e2e2e8','stroke-width':'1',}).move(devX,y).addClass('router');devCircle.fill(backgdimg);devCircle.on('click',function(e){var circleobj=document.getElementById(this);var nameattr=circleobj.getAttribute('name');if(nameattr=='selectedroute'){var popDevData=document.querySelector('#PopDevDataDiv');if(popDevData)popDevData.remove();RestoreCircleColor();if(document.getElementById('polygon')!=null){document.getElementById('polygon').remove();}
return;}
RestoreCircleColor();circleobj.setAttribute('name','selectedroute');var oldPop=document.getElementById('PopDevDataDiv');if(oldPop)oldPop.remove();var devinfotop=devHeight+y+1;if(document.getElementById('polygon')!=null){document.getElementById('polygon').remove();}
var circleX=circleobj.cx.baseVal.value;var circleY=circleobj.cy.baseVal.value;var circleR=circleobj.r.baseVal.value;var pXTop=circleX;var pYTop=circleY+circleR-20;var pXLeft=circleX-12;var pXRight=circleX+12;var pYBottom=pYTop+20;var polygonPoint=[[pXTop,pYTop],[pXRight,pYBottom],[pXLeft,pYBottom],];var devPolygon=draw.polygon(polygonPoint).attr({fill:'#fff',stroke:'#fff','stroke-width':1,id:'polygon'});TopoShowPopData(circleobj,devinfotop);});if(data.accdevCount>0){var accdevCircle=draw.circle(20).attr({fill:'#00b7ef'}).move(devX+(devHeight*3)/4,y+(devHeight*3)/4);var accdevCountText=draw.text(data.accdevCount.toString()).fill('#fff').move(devX+(devHeight*3)/4+10,y+(devHeight*3)/4+12);accdevCountText.font({family:'Helvetica',size:11,anchor:'middle',leading:'1em',});if(data.accdevCount>9){accdevCountText.dx(-1);}}
var hostNameText=draw.text(data.HostName).fill('#262727').move(x+w/2,y+devHeight+5).addClass('hostText');hostNameText.font({family:'Helvetica',size:14,anchor:'middle',weight:'bold',});hostNameText.on('click',function(e){var ipaddr=data.IPAddr;var abs=window.top.location.href;var protocolStr=abs.match(/\w+:/)[0];var urlStr=protocolStr+'//'+ipaddr;window.open(urlStr);});var macText=draw.text('MAC:'+data.MACAddr).fill('#a4a6a6').move(x+w/2,y+devHeight+25);macText.font({family:'Helvetica',size:11,anchor:'middle',});var ipText=draw.text('IP: '+data.IPAddr).fill('#a4a6a6').move(x+w/2,y+devHeight+40);ipText.font({family:'Helvetica',size:11,anchor:'middle',});}
function drawController(x,y,data){drawDevice(x,y,CONTROLLER_CONTAINER_WIDTH,CONTROLLER_CONTAINER_HEIGHT,110,data,'control');}
function drawAgent(x,y,data){drawDevice(x,y,AGENT_CONTAINER_WIDTH,AGENT_CONTAINER_HEIGHT,90,data,'agent');}
var patterncontrol=draw.pattern().attr({id:'backgroundimg',patternUnits:'objectBoundingBox',width:'1',height:'1',});patterncontrol.image(L.resource('cbi/topov2_router.svg')).attr({preserveAspectRatio:'none meet',x:'0',y:'0',width:'115',height:'115',});var patternagent=draw.pattern().attr({id:'agentbackgroundimg',patternUnits:'objectBoundingBox',width:'1',height:'1',});patternagent.image(L.resource('cbi/topov2_router.svg')).attr({preserveAspectRatio:'none meet',x:'0',y:'0',width:'90',height:'90',});var patterneth=draw.pattern().attr({id:'ethimg',patternUnits:'objectBoundingBox',width:'1',height:'1',});patterneth.image(L.resource('icons/topov2_ethconn.png')).attr({preserveAspectRatio:'none meet',x:'0',y:'0',width:'20',height:'20',});var patternwlan=draw.pattern().attr({id:'wlanimg',patternUnits:'objectBoundingBox',width:'1',height:'1',});patternwlan.image(L.resource('icons/topov2_wlanconn.png')).attr({preserveAspectRatio:'none meet',x:'0',y:'0',width:'20',height:'20',});var controllerData={accdevCount:topodata.controllerData.accdevCount,MACAddr:topodata.controllerData.MacAddr,HostName:topodata.controllerData.DeviceName,IPAddr:topodata.controllerData.IpAddr,instID:topodata.controllerData.instID,};drawController(TOPO_CONTAINER_WIDTH/2-CONTROLLER_CONTAINER_WIDTH/2,0,controllerData);function getConnBackgroundImg(accessType){var img='#ccc';if(accessType=='ETH'){img='url(#ethimg)';}else if(accessType=='2.4G'||accessType=='5G'||accessType=='6G'){img='url(#wlanimg)';}
return img;}
function drawConnectedLine(pointArray,accessType){var connimg=getConnBackgroundImg(accessType);draw.polyline(pointArray).fill('none').stroke({width:0.5,color:'#999'});var d=pointArray.pop();var devCircle=draw.circle(20).move(d[0]-10,d[1]).attr({fill:connimg});}
function getLayerAgentsAxis_X(count,parentX,layer,topodata){var output=[];if(layer==2&&topodata.agentlay3!=undefined&&topodata.agentlay2.MGET_INST_NUM<=topodata.agentlay3.MGET_INST_NUM){AGENT_CONTAINER_WIDTH=300;}else{AGENT_CONTAINER_WIDTH=118;}
var oneAgentWidth=AGENT_CONTAINER_WIDTH+2;var startX=parentX-((AGENT_CONTAINER_WIDTH+2)*count)/2;if(layer==1){oneAgentWidth=TOPO_CONTAINER_WIDTH/count;startX=0;}
if((layer==2&&topodata.agentlay1.MGET_INST_NUM==2&&count>=5)||(layer==3&&topodata.agentlay1.MGET_INST_NUM==2&&topodata.agentlay2.MGET_INST_NUM==1&&count>3)){startX=TOPO_CONTAINER_WIDTH/6;}
for(var i=0;i<count;i++){output.push(startX+oneAgentWidth/2);startX=startX+oneAgentWidth;}
return output;}
function drawLayerAgents(agentData,parentX,num,count,topodata){var agentAxis_x_array=getLayerAgentsAxis_X(count,parentX,num,topodata);agentAxis_x_array.forEach(function(x,i){var perdata=agentData[i];drawAgent(x-AGENT_CONTAINER_WIDTH/2,LAYER_AGENT_AXIS_Y+210*num,perdata);drawConnectedLine([[parentX,210*num-30],[parentX,210*num-30+20],[x,210*num-30+20],[x,210*num-30+30],],perdata.AccessType);});}
var MAX_AGENT_NUM=8;var maxlayer=3;for(var i=1;i<maxlayer;i++){if(topodata['agentlay'+i]!==undefined&&topodata['agentlay'+i].MGET_INST_NUM>0){var leftnum=MAX_AGENT_NUM;for(var j=1;j<i;j++){leftnum-=topodata['agentlay'+j].MGET_INST_NUM;}
var allowNum=Math.min(leftnum,topodata['agentlay'+i].MGET_INST_NUM);var AgentLayObj=Array.from(document.getElementsByTagName('circle')).filter(function(circle){return circle.getAttribute('InstID_Dev')!==null&&circle.getAttribute('InstID_Dev')!=='';});for(var m=0;m<AgentLayObj.length;m++){if(allowNum<=0)break;var parentid=AgentLayObj[m].getAttribute('InstID_Dev');var layagentArray=[];var layagentnum=0;for(var n=1;n<=topodata['agentlay'+i].MGET_INST_NUM;n++){var perlaydata=topodata['agentlay'+i][n];if(perlaydata.instID_Parent===parentid){layagentArray.push({accdevCount:perlaydata.accdevCount,MACAddr:perlaydata.MacAddr,HostName:perlaydata.DeviceName,IPAddr:perlaydata.IpAddr,instID:perlaydata.instID,AccessType:perlaydata.AccessType,});layagentnum++;if(layagentnum>=allowNum)break;}}
if(layagentArray.length>0){var x=AgentLayObj[m].cx.baseVal.value;layagentArray['children']=layagentArray.length;drawLayerAgents(layagentArray,x,i,layagentnum,topodata);allowNum-=layagentnum;}}}else{break;}}},render:function(data){var CONTROLLER_CONTAINER_WIDTH=180;var CONTROLLER_CONTAINER_HEIGHT=170;var AGENT_CONTAINER_WIDTH=118;var AGENT_CONTAINER_HEIGHT=150;var LAYER_AGENT_AXIS_Y=30;var MAX_AGENT_NUM=8;var maxlayer=3;var topoData=JSON.parse(data[0].data)||{};var apData=JSON.parse(data[1].data)||{};var clientData=JSON.parse(data[2].data)||{};console.log('topoData->',topoData);console.log('apData->',apData);console.log('clientData->',clientData);var data=topoData.GetTopoData;if(!Array.from){Array.from=function(el){return Array.apply(this,el);};}
var svgobj=Array.from(document.getElementsByTagName('svg'));if(svgobj.length>0){svgobj.forEach(function(item){if(item!=null){var userAgent=navigator.userAgent;if((userAgent.indexOf('compatible')>-1&&userAgent.indexOf('MSIE')>-1)||/Trident\/7./.test(navigator.userAgent)){item.parentNode.removeChild(item);}else{item.remove();}}});}
var TOPO_CONTAINER_WIDTH=960;var svgHeight=200;var leftNum=0;for(var i=1;i<maxlayer;i++){if(data['agentlay'+i]!=undefined){if(data['agentlay'+i].MGET_INST_NUM>0){leftNum=MAX_AGENT_NUM-data['agentlay'+i].MGET_INST_NUM;if(leftNum>=0){svgHeight+=200;}else{break;}}}}
var container=E('div',{id:'topoPageContent',style:'margin-left: -215px;'});var svgContainer=E('div',{id:'svg-area'});var src=L.env.resource+'/svg.min.js';var script=E('script',{type:'text/javascript',src:src});document.querySelector('body').appendChild(script);var viewInstance=this;script.onload=function(){var draw=SVG('svg-area').attr('id','svg_topo').size(TOPO_CONTAINER_WIDTH,svgHeight);viewInstance.initial_template_svg(TOPO_CONTAINER_WIDTH,CONTROLLER_CONTAINER_WIDTH,CONTROLLER_CONTAINER_HEIGHT,AGENT_CONTAINER_WIDTH,AGENT_CONTAINER_HEIGHT,LAYER_AGENT_AXIS_Y,svgHeight,draw,data);};var apContainer=E('div',{class:'cbi-section',id:'topo-ap-form'});var apContent=E('div',{class:'ap-content-container'});apContent.append(E('br'));const clickHandler=function(event){event.stopPropagation();const arrow=event.currentTarget.querySelector('.arrow');const content=event.currentTarget.nextElementSibling;if(!arrow||!content)return;if(arrow.textContent==='▼'){arrow.textContent='▶';content.style.display='none';}else{arrow.textContent='▼';content.style.display='';}};var arrow=document.createElement('span');arrow.className='arrow';arrow.textContent='▼';arrow.style.color='#404040';arrow.style.marginRight='10px';var titleobj=E('h2',{name:'content',style:'color: #018fd5; font-size: 16px; border-bottom: 1px solid #e0e0e1;',},_('ALL APs'));titleobj.prepend(arrow);titleobj.addEventListener('click',clickHandler);apContainer.append(titleobj);apContainer.append(apContent);function setupTableInlineEdit(table){table.addEventListener('click',function(e){const target=e.target;if(target.classList.contains('modify-btn')){startEditing(target);}
if(target.classList.contains('save-btn')){saveEditing(target);}
if(target.classList.contains('cancel-btn')){cancelEditing(target);}});}
function startEditing(button){const row=button.closest('tr');const hostnameCell=row.cells[0];const operateCell=row.cells[row.cells.length-1];hostnameCell._originalValue=hostnameCell.textContent;const input=E('input',{type:'text',value:hostnameCell._originalValue,class:'edit-input',style:'width: 100%; padding: 4px; border: 1px solid #ddd; border-radius: 3px;',});hostnameCell.innerHTML='';hostnameCell.appendChild(input);const saveBtn=E('button',{class:'save-btn',style:'margin-right: 5px; padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;',},[_('OK')]);const cancelBtn=E('button',{class:'cancel-btn',style:'padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;',},[_('Cancel')]);operateCell.innerHTML='';operateCell.appendChild(saveBtn);operateCell.appendChild(cancelBtn);input.focus();}
function saveEditing(saveBtn){const row=saveBtn.closest('tr');const hostnameCell=row.cells[0];const inst=row.id;const operateCell=row.cells[5];const input=hostnameCell.querySelector('.edit-input');const newValue=input.value.trim()||hostnameCell._originalValue;hostnameCell.textContent=newValue;const modifyBtn=E('button',{class:'modify-btn',style:'padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;','data-row-id':row.dataset.rowId,},[_('Modify')]);operateCell.innerHTML='';operateCell.appendChild(modifyBtn);const result={};result.InstIdentity=inst;result.Alias=newValue;return viewInstance.callGetPageLoad('webagent_mesh_set_alias_info',JSON.stringify(result)).then(()=>{setTimeout(()=>window.location.reload(),500);}).catch((err)=>{ui.addNotification(null,E('p',_('Save failed: ')+err.message));throw err;});}
function cancelEditing(cancelBtn){const row=cancelBtn.closest('tr');const hostnameCell=row.cells[0];const operateCell=row.cells[5];hostnameCell.textContent=hostnameCell._originalValue;const modifyBtn=E('button',{class:'modify-btn',style:'padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;','data-row-id':row.dataset.rowId,},[_('Modify')]);operateCell.innerHTML='';operateCell.appendChild(modifyBtn);}
var apTbl=E('table',{class:'table',style:'border: 1px solid #ddd; border-radius: 10px;'},[E('tr',{class:'tr table-titles',style:'background-color: #f0f2f5;'},[E('th',{class:'th'},[_('AP Name')]),E('th',{class:'th'},[_('IP')]),E('th',{class:'th'},[_('MAC')]),E('th',{class:'th'},[_('Role')]),E('th',{class:'th'},[_('Backhaul')]),E('th',{class:'th'},[_('Operate area')]),]),]);setupTableInlineEdit(apTbl);if(apData.GetALLAP.MGET_INST_NUM==0){var apRow=E('tr',{},[E('td',{style:'padding: 8px; text-align: left; font-style: italic; color: #999;',colspan:4,},[E('img',{src:L.resource('icons/info_s.png'),style:'width: 16px; height: 16px; margin-right: 8px;',}),'There are no data now.',]),]);apTbl.appendChild(apRow);}else{for(var i=1;i<=apData.GetALLAP.MGET_INST_NUM;i++){var returnHz=apData.GetALLAP[i].AccessType+'/'+apData.GetALLAP[i].BhStaRssi+_('dBm');if(apData.GetALLAP[i].role=='controller'){returnHz='/';}else if(apData.GetALLAP[i].AccessType=='ETH'){returnHz='ETH';}
var apRow=E('tr',{class:'tr','data-row-id':i,id:apData.GetALLAP[i].MacAddr},[E('td',{class:'td'},[apData.GetALLAP[i].DeviceName]),E('td',{class:'td'},[apData.GetALLAP[i].IpAddr]),E('td',{class:'td'},[apData.GetALLAP[i].MacAddr]),E('td',{class:'td'},[apData.GetALLAP[i].role]),E('td',{class:'td'},[returnHz]),E('td',{class:'td'},[E('button',{class:'modify-btn',style:'padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;','data-row-id':i,},[_('Modify')]),]),]);apTbl.appendChild(apRow);}}
apContent.append(apTbl);container.append(svgContainer);container.append(apContainer);var clientContainer=E('div',{class:'cbi-section',id:'topo-client-form'});var clientContent=E('div',{class:'clinet-content-container'});clientContent.append(E('br'));var arrow1=document.createElement('span');arrow1.className='arrow';arrow1.textContent='▼';arrow1.style.color='#404040';arrow1.style.marginRight='10px';var titleobj1=E('h2',{name:'content',style:'color: #018fd5; font-size: 16px; border-bottom: 1px solid #e0e0e1;',},_('ALL Clients'));titleobj1.prepend(arrow1);titleobj1.addEventListener('click',clickHandler);clientContainer.append(titleobj1);clientContainer.append(clientContent);var clientTbl=E('table',{class:'table',style:'border: 1px solid #ddd;'},[E('tr',{class:'tr table-titles',style:'background-color: #f0f2f5;'},[E('th',{class:'th'},[_('Client Name')]),E('th',{class:'th'},[_('Upstream device')]),E('th',{class:'th'},[_('Associated Band')]),E('th',{class:'th'},[_('RSSI')]),E('th',{class:'th'},[_('SNR')]),E('th',{class:'th'},[_('Operate area')]),]),]);setupTableInlineEdit(clientTbl);if(clientData.GetALLClients.MGET_INST_NUM==0){var clientRow=E('tr',{},[E('td',{style:'padding: 8px; text-align: left; font-style: italic; color: #999;',colspan:4,},[E('img',{src:L.resource('icons/info_s.png'),style:'width: 16px; height: 16px; margin-right: 8px;',}),'There are no data now.',]),]);clientTbl.appendChild(clientRow);}else{for(var i=1;i<=clientData.GetALLClients.MGET_INST_NUM;i++){var RSSI=clientData.GetALLClients[i].Rssi+_('dBm');var SNR=clientData.GetALLClients[i].SNR;var relateHz=clientData.GetALLClients[i].AccessType;if(relateHz=='ETH'){RSSI='/';SNR='/';}
var clientRow=E('tr',{class:'tr',id:clientData.GetALLClients[i].MacAddr,'data-row-id':i,},[E('td',{class:'td'},[clientData.GetALLClients[i].HostName]),E('td',{class:'td'},[clientData.GetALLClients[i].parentType]),E('td',{class:'td'},[relateHz]),E('td',{class:'td'},[RSSI]),E('td',{class:'td'},[SNR]),E('td',{class:'td'},[E('button',{class:'modify-btn',style:'padding: 4px 10px; border-radius: 4px; background-color: #f0f0f0; color: #333; border: 1px solid #d9d9d9; cursor: pointer;','data-row-id':i,},[_('Modify')]),]),]);clientTbl.appendChild(clientRow);}}
clientContent.append(clientTbl);container.append(clientContainer);return container;},handleSave:null,handleSaveApply:null,handleSaveInst:null,handleReset:null,});