'use strict';'require view';'require uci';'require form';function convertToMinutes(input){if(!input||typeof input!=='string'){return'0m';}
const match=input.match(/^(\d+)([hm])$/);if(!match){return'0m';}
const value=parseInt(match[1],10);const unit=match[2];let result;switch(unit){case'h':result=value*60;break;case'm':result=value;break;default:return'0m';}
return`${result}m`;}
return view.extend({load:function(){return uci.load('dhcp')},render:function(data){var lanConfig=uci.get('dhcp','lan')||{};let m,s,o;m=new form.Map('dhcp',_('IPv6 - RA Service'),_('This page provides the function of LAN (IPv6) parameter(s) configuration.'));s=m.section(form.NamedSection,'lan',_('RA Service'));var raService=s.option(form.ListValue,'ra',_('RA Service'));raService.widget='radio';raService.value('server',_('On'));raService.value('disabled',_('Off'));raService.default=lanConfig.ra||'disabled';raService.rmempty=false;var MTU=s.option(form.Value,'ra_mtu',_('MTU'),_('Please enter a value between 1280 and 1500.'));MTU.default=lanConfig.ra_mtu||'1500';MTU.validate=function(section_id,value){if(value<1280||value>1500)
return _("Please enter a value between 1280 and 1500.")
return true};MTU.rmempty=false;var Preference=s.option(form.ListValue,'ra_preference',_('Preference'));Preference.value('high',_('High'));Preference.value('medium',_('Middle'));Preference.value('low',_('Low'));Preference.default=lanConfig.ra_preference||'medium';Preference.rmempty=false;var minRetryInterval=s.option(form.Value,'ra_mininterval',_('Minimum Retry Interval'),_('Please enter a value between 3 and 1350.'));minRetryInterval.default=lanConfig.ra_mininterval||'200';minRetryInterval.validate=function(section_id,value){if(value<3||value>1350)
return _("Please enter a value between 3 and 1350.")
return true};minRetryInterval.rmempty=false;var maxRetryInterval=s.option(form.Value,'ra_maxinterval',_('Maximum Retry Interval'),_('Please enter a value between 4 and 1800.'));maxRetryInterval.default=lanConfig.ra_maxinterval||'600';maxRetryInterval.validate=function(section_id,value){if(value<4||value>1800)
return _("Please enter a value between 4 and 1800.")
return true};maxRetryInterval.rmempty=false;var mObj=s.option(form.ListValue,'ra_m',_('M'));mObj.widget='radio';mObj.value('1',_('On'));mObj.value('0',_('Off'));var raFlags=lanConfig.ra_flags||'';var hasManagedConfig=raFlags.includes('managed-config');mObj.default=hasManagedConfig?'1':'0';mObj.rmempty=false;var oObj=s.option(form.ListValue,'ra_o',_('O'));oObj.widget='radio';oObj.value('1',_('On'));oObj.value('0',_('Off'));var hasOtherConfig=raFlags.includes('other-config');oObj.default=hasOtherConfig?'1':'0';oObj.rmempty=false;m.save=function(){return Promise.resolve().then(()=>{var raServiceVal=raService.formvalue('lan');var MTUVal=MTU.formvalue('lan');var PreferenceVal=Preference.formvalue('lan');var minRetryIntervalVal=minRetryInterval.formvalue('lan');var maxRetryIntervalVal=maxRetryInterval.formvalue('lan');var mVal=mObj.formvalue('lan')=='1'?'managed-config':'';var oVal=oObj.formvalue('lan')=='1'?'other-config':'';var raFlagsVal=mVal+' '+oVal
uci.set('dhcp','lan','ra',raServiceVal);uci.set('dhcp','lan','ra_mtu',MTUVal);uci.set('dhcp','lan','ra_preference',PreferenceVal);uci.set('dhcp','lan','ra_mininterval',minRetryIntervalVal);uci.set('dhcp','lan','ra_maxinterval',maxRetryIntervalVal);uci.set('dhcp','lan','ra_flags',raFlagsVal);return uci.save().then(()=>{return true;});});};return m.render();}});