'use strict';'require view';'require dom';'require poll';'require baseclass';'require fs';'require network';'require ui';'require uci';return view.extend({load:function(){return Promise.all([fs.trimmed('/proc/sys/net/netfilter/nf_conntrack_count'),fs.trimmed('/proc/sys/net/netfilter/nf_conntrack_max'),network.getWANNetworks(),network.getWAN6Networks(),uci.load('firewall')]);},render:function(data){var ct_count=+data[0],ct_max=+data[1],wan_nets=data[2],wan6_nets=data[3];var wanmac=uci.get('network','wan','macaddr')||'';var wan_net=null
if(wan_nets&&wan_nets.length>0){wan_nets.forEach(item=>{if(item.sid=='wan'){wan_net=item}});}
var lla=wan_net?wan_net.getIP6Addrs():'::';var gua=wan6_nets[0]?wan6_nets[0].getIP6Addrs():'::';var v6up=wan6_nets[0]?wan6_nets[0]._ubus('up'):false;var ipv6_connected=(lla!=='::'&&gua!=='::'&&v6up!==false);var natStatus=uci.get('firewall','wanzone','masq')==='1'?'On':'Off';var fields=[_('Type'),wan_net?wan_net.getI18n():_('Not connected'),_('IP Version'),'IPv4/v6',_('NAT'),natStatus,_('IP Address'),wan_net?wan_net.getIPAddrs():'0.0.0.0/0.0.0.0',_('DNS'),wan_net?wan_net.getDNSAddrs():'0.0.0.0/0.0.0.0/0.0.0.0',_('IPv4 Gateway'),wan_net?wan_net.getGatewayAddr():'0.0.0.0',_('IPv4 Connection Status'),wan_net?(wan_net._ubus('up')?_('Connected'):_('Disconnected')):_('Disconnected'),_('IPv4 Online Duration'),wan_net?(wan_net.getUptime()>0?'%t'.format(wan_net.getUptime()):_('0h 0m 0s')):_('0h 0m 0s'),_('LLA'),lla,_('GUA'),gua,_('DNS'),wan6_nets[0]?wan6_nets[0].getDNS6Addrs():'::/::/::',_('IPv6 Gateway'),wan6_nets[0]?wan6_nets[0].getGateway6Addr():'::',_('IPv6 Connection Status'),ipv6_connected?_('Connected'):_('Disconnected'),_('IPv6 Online Duration'),wan6_nets[0]?(wan6_nets[0].getUptime()>0?'%t'.format(wan6_nets[0].getUptime()):_('0h 0m 0s')):_('0h 0m 0s'),_('WAN MAC'),wanmac,];var table=E('table',{'class':'table'});table.appendChild(E('tr',{'class':'tr','style':'background-color: #C8E6FE;'},[E('td',{'class':'td left emFont','width':'40%'},[_('Connection Name')]),E('td',{'class':'td left'},['WAN'])]));for(var i=0;i<fields.length;i+=2){var row=E('tr',{'class':'tr'},[E('td',{'class':'td left emFont','width':'40%'},[fields[i]]),E('td',{'class':'td left'},[(fields[i+1]!=null)?fields[i+1]:'?'])]);if(i/2%2!==0){row.style.backgroundColor='#EFF8FF';}
table.appendChild(row);}
var container=E('div')
container.appendChild(E('h3',{'name':'content'},_('WAN Connection Status')))
container.appendChild(E('span',_('This page shows the status of WAN.')))
container.appendChild(E('br'))
container.appendChild(E('br'))
container.appendChild(table)
container.appendChild(E('div',{'style':'text-align: right; margin-top: 20px'},E('button',{'class':'btn cbi-button refreshBtn','style':'min-width: 100px','click':ui.createHandlerFn(this,function(){window.location.reload();})},_('Refresh'))));return container;},handleSaveApply:null,handleSave:null,handleReset:null,handleSaveInst:null});