'use strict';'require view';'require rpc';'require uci';'require ui';'require form';'require dom';const encryptionMap={"No Security":{"BeaconType":"None"},"WPA2-PSK-AES":{"BeaconType":"11i","IEEE11iAuthenticationMode":"PSKAuthentication","IEEE11iEncryptionModes":"AESEncryption"},"WPA/WPA2-PSK-AES":{"BeaconType":"WPAand11i","WPAAuthenticationMode":"PSKAuthentication","IEEE11iAuthenticationMode":"PSKAuthentication","WPAEncryptionModes":"AESEncryption","IEEE11iEncryptionModes":"AESEncryption"},"WPA/WPA2-PSK-TKIP/AES":{"BeaconType":"WPAand11i","WPAAuthenticationMode":"PSKAuthentication","IEEE11iAuthenticationMode":"PSKAuthentication","WPAEncryptionModes":"TKIPandAESEncryption","IEEE11iEncryptionModes":"TKIPandAESEncryption"},"WPA3(SAE)":{"BeaconType":"WPA3","WPA3AuthenticationMode":"SAEAuthentication","WPA3EncryptionModes":"AESEncryption"},"WPA2-PSK/WPA3-SAE-AES":{"BeaconType":"11iandWPA3","IEEE11iAuthenticationMode":"PSKAuthentication","WPA3AuthenticationMode":"SAEAuthentication","IEEE11iEncryptionModes":"AESEncryption","WPA3EncryptionModes":"AESEncryption"},};const wlanBsHandle=(obj)=>{let enableList=[];if(obj.BandSteeringEnable){enableList=[5]}
if(obj.BandSteeringEnableSSID2){enableList=[...enableList,6]}
if(obj.BandSteeringEnableSSID3){enableList=[...enableList,7]}
if(obj.BandSteeringEnableSSID4){enableList=[...enableList,8]}
return enableList}
return view.extend({callGetPageLoad:rpc.declare({object:'luci',method:'usecmapi',params:['method','data'],expect:{}}),load:function(){return Promise.all([this.callGetPageLoad('webagent_get_wlanssidconfig','{}'),this.callGetPageLoad('webagent_get_bandsteering','{}')]);},containsObj:function(object1,object2){for(var index in object2){if(object2[index]!=object1[index]){return false;}}
return true;},render:function(data){let ssidData=JSON.parse(data[0].data);const wlanBS=wlanBsHandle((JSON.parse(data[1].data)||{}).BandSteering||{});let m,s,o;m=new form.JSONMap(ssidData,_('WLAN SSID Configuration'));s=m.section(form.GridSection,'WLANSSID');s.anonymous=true;const option_names=Object.keys(ssidData.WLANSSID);let passVal='';for(let i=0;i<option_names.length;i++){var option_name=option_names[i];if(i<=3){ssidData.WLANSSID[option_name]['Alias']='SSID'+(i+1)+'(2.4G)';}else{ssidData.WLANSSID[option_name]['Alias']='SSID'+(i+1)+'(5G)';}
let beaconType=ssidData.WLANSSID[option_name]['BeaconType'];let wpaAuthMode=ssidData.WLANSSID[option_name]['WPAAuthenticationMode'];let wpaEncryptType=ssidData.WLANSSID[option_name]['WPAEncryptionModes'];let wpa3AuthMode=ssidData.WLANSSID[option_name]['WPA3AuthenticationMode'];let wpa3EncryptType=ssidData.WLANSSID[option_name]['WPA3EncryptionModes'];let _11iAuthMode=ssidData.WLANSSID[option_name]['IEEE11iAuthenticationMode'];let _11iEncryptType=ssidData.WLANSSID[option_name]['IEEE11iEncryptionModes'];passVal=ssidData.WLANSSID[option_name]['KeyPassphrase'];if(ssidData.WLANSSID[option_name]['SSIDAdvertisementEnabled']===1){ssidData.WLANSSID[option_name]['SSIDAdvertisementEnabled']=0}else{ssidData.WLANSSID[option_name]['SSIDAdvertisementEnabled']=1}
for(let key in encryptionMap){let entry=encryptionMap[key];let match=true;let currentEncryption={};currentEncryption.BeaconType=beaconType;currentEncryption.WPAAuthenticationMode=wpaAuthMode;currentEncryption.WPAEncryptionModes=wpaEncryptType;currentEncryption.IEEE11iAuthenticationMode=_11iAuthMode;currentEncryption.IEEE11iEncryptionModes=_11iEncryptType;currentEncryption.WPA3AuthenticationMode=wpa3AuthMode;currentEncryption.WPA3EncryptionModes=wpa3EncryptType;match=this.containsObj(currentEncryption,entry);if(match){ssidData.WLANSSID[option_name]['encryption']=key;break;}}}
o=s.option(form.HiddenValue,'Alias');o.readonly=true;o=s.option(form.Flag,'Enable',_('SSID Enable'));o.rmempty=false;o.modalonly=true;o=s.option(form.Value,'SSID',_('SSID Name'));o.rmempty=false;o.modalonly=true;o.datatype="rangelength(1,32)";o=s.option(form.ListValue,'ForceWiFi5',_('Mode'));o.value('1','b/g/n');o.rmempty=false;o.depends('Alias','SSID4(2.4G)');o.depends('Alias','SSID8(5G)');o.modalonly=true;o=s.option(form.Flag,'SSIDAdvertisementEnabled',_('SSID Hide'));o.rmempty=false;o.modalonly=true;o=s.option(form.ListValue,'encryption',_('Encryption Type'));for(let key in encryptionMap){o.value(key,key);}
o.rmempty=false;o.modalonly=true;o=s.option(form.Value,'KeyPassphrase',_('WPA Passphrase'));o.modalonly=true;o.password=true;o.datatype="rangelength(8,63)";o.depends('encryption','WPA2-PSK-AES');o.depends('encryption','WPA/WPA2-PSK-TKIP/AES');o.depends('encryption','WPA3(SAE)');o.depends('encryption','WPA2-PSK/WPA3-SAE-AES');o.depends('encryption','WPA/WPA2-PSK-AES');o=s.option(form.Flag,'X_ZTE-COM_SSIDIsolation',_('SSID Isolation'));o.rmempty=false;o.modalonly=true;o=s.option(form.Value,'X_ZTE-COM_MaxUserNum',_('Maximum Clients'));o.rmempty=false;o.modalonly=true;o.datatype='max(32)';const viewInstance=this;s.handleModalSave=function(section_id){const mapNode=this.getActiveModalMap();const invalidInputs=mapNode.querySelectorAll('input.cbi-input-invalid');if(invalidInputs.length>0){return null;}
let activeMap=dom.findClassInstance(mapNode);activeMap.save(null,true);const filteredData=activeMap.data.data[activeMap.section];let encryptionValue=filteredData['encryption'];if(encryptionValue==='No Security'){filteredData['KeyPassphrase']=passVal;}
if(encryptionMap[encryptionValue]){filteredData['BeaconType']=encryptionMap[encryptionValue].BeaconType;if(encryptionMap[encryptionValue].WPAAuthenticationMode!==undefined){filteredData['WPAAuthenticationMode']=encryptionMap[encryptionValue].WPAAuthenticationMode;}
if(encryptionMap[encryptionValue].WPAEncryptionModes!==undefined){filteredData['WPAEncryptionModes']=encryptionMap[encryptionValue].WPAEncryptionModes;}
if(encryptionMap[encryptionValue].WPA3AuthenticationMode!==undefined){filteredData['WPA3AuthenticationMode']=encryptionMap[encryptionValue].WPA3AuthenticationMode;}
if(encryptionMap[encryptionValue].WPA3EncryptionModes!==undefined){filteredData['WPA3EncryptionModes']=encryptionMap[encryptionValue].WPA3EncryptionModes;}
if(encryptionMap[encryptionValue].IEEE11iAuthenticationMode!==undefined){filteredData['IEEE11iAuthenticationMode']=encryptionMap[encryptionValue]['IEEE11iAuthenticationMode'];}
if(encryptionMap[encryptionValue].IEEE11iEncryptionModes!==undefined){filteredData['IEEE11iEncryptionModes']=encryptionMap[encryptionValue]['IEEE11iEncryptionModes'];}}
if(filteredData['Enable']==='1'){filteredData['Enable']=true;}else{filteredData['Enable']=false;}
if(filteredData['SSIDAdvertisementEnabled']==='1'){filteredData['SSIDAdvertisementEnabled']=false;}else{filteredData['SSIDAdvertisementEnabled']=true;}
if(filteredData['X_ZTE-COM_SSIDIsolation']==='1'){filteredData['X_ZTE-COM_SSIDIsolation']=true;}else{filteredData['X_ZTE-COM_SSIDIsolation']=false;}
filteredData['X_ZTE-COM_MaxUserNum']=parseInt(filteredData['X_ZTE-COM_MaxUserNum']);if(filteredData['ForceWiFi5']!=undefined){filteredData['ForceWiFi5']=parseInt(filteredData['ForceWiFi5']);}else{filteredData['ForceWiFi5']=0;}
viewInstance.callGetPageLoad('webagent_set_wlanssidconfig',JSON.stringify(filteredData)).then(()=>{ui.addNotification(null,E('p',_('Settings saved successfully. Reloading...')));setTimeout(()=>window.location.reload(),500);}).catch(err=>{console.error('Save failed:',err);});return false;}
return m.render().then((mapEl)=>{setTimeout(function(){const rows=document.querySelectorAll('#cbi-json-WLANSSID .cbi-button-edit')
rows.forEach((el)=>{const eventParent=el.parentNode.parentNode.parentNode
const ssid=eventParent.querySelector('.cbi-value-field').textContent
const match=ssid.match(/(\d+)(?=\(2\.4G\)|\(5G\))/);const ssidNumber=match?parseInt(match[0],10):null;if(wlanBS.includes(ssidNumber)){el.style.display='none'}})},0);const observer=new MutationObserver((mutations)=>{mutations.forEach(mutation=>{if(mutation.addedNodes.length){mutation.addedNodes.forEach(node=>{if(node.classList&&node.classList.contains('button-row')){initModalContent(node);}});}});});observer.observe(document.body,{childList:true,subtree:true});const initModalContent=(modal)=>{const section=modal.closest('.cbi-modal').querySelector('.cbi-section');if(!section)return;const ForceWiFi5Select=section.querySelector('[data-name="ForceWiFi5"] select');const Alias=section.querySelector('[data-name="Alias"] input');var AliasVal="";if(Alias){AliasVal=Alias.value;}
const ForceWiFi55g=[{value:'1',text:'a/n/ac'},{value:'0',text:'a/n/ac/ax'}];const ForceWiFi52g=[{value:'1',text:'b/g/n'},{value:'0',text:'b/g/n/ax'}];if(AliasVal==="SSID8(5G)"){ForceWiFi5Select.innerHTML='';ForceWiFi55g.forEach(mode=>{ForceWiFi5Select.add(new Option(mode.text,mode.value));});ForceWiFi5Select.value=ssidData.WLANSSID[7]['ForceWiFi5'];}else if(AliasVal==="SSID4(2.4G)"){ForceWiFi5Select.innerHTML='';ForceWiFi52g.forEach(mode=>{ForceWiFi5Select.add(new Option(mode.text,mode.value));});ForceWiFi5Select.value=ssidData.WLANSSID[3]['ForceWiFi5'];}};return mapEl});},handleSave:null,handleSaveApply:null,handleSaveInst:null,handleReset:null,});