'use strict';'require view';'require poll';'require ui';'require uci';'require rpc';'require form';var callRcList=rpc.declare({object:'rc',method:'list',params:['name'],expect:{'':{}},filter:function(res){for(var k in res)
return+res[k].enabled;return null;}});var callGetLocaltime=rpc.declare({object:'system',method:'info',expect:{localtime:0}});var callTimezone=rpc.declare({object:'luci',method:'getTimezones',expect:{'':{}}});function formatTime(epoch){var date=new Date(epoch*1000);return'%04d-%02d-%02d %02d:%02d:%02d'.format(date.getUTCFullYear(),date.getUTCMonth()+1,date.getUTCDate(),date.getUTCHours(),date.getUTCMinutes(),date.getUTCSeconds());}
return view.extend({load:function(){return Promise.all([callRcList('sysntpd'),callTimezone(),callGetLocaltime(),uci.load('luci'),uci.load('system')]);},render:function(data){var ntpd_enabled=data[0],timezones=data[1],localtime=data[2],m,s,o;m=new form.Map('system',_('SNTP'),_('This page provides the function of SNTP parameter(s) configuration.'));m.chain('luci');s=m.section(form.TypedSection,'system');s.anonymous=true;s.addremove=false;o=s.option(form.DummyValue,'_systime',_('Current Date And Time'));o.rawhtml=true;o.cfgvalue=function(){return`<input id="localtime" type="text" readonly class="cbi-input-text" value="${formatTime(localtime)}" />`;};o=s.option(form.ListValue,'zonename',_('Time Zone'));o.value('UTC');var zones=Object.keys(timezones||{}).sort();for(var i=0;i<zones.length;i++){var zone=zones[i];var tz=timezones[zone]?.tzstring||'';var label=`${zone} (${tz})`;o.value(zone,label);}
o.write=function(section_id,formvalue){var tz=timezones[formvalue]?timezones[formvalue].tzstring:null;uci.set('system',section_id,'zonename',formvalue);uci.set('system',section_id,'timezone',tz);};if(L.hasSystemFeature('sysntpd')){o=s.option(form.DynamicList,'server',_('NTP server candidates'),_('List of upstream NTP server candidates with which to synchronize.'));o.datatype='host(0)';o.ucisection='ntp';o.load=function(section_id){return uci.get('system','ntp','server');};o.write=function(section_id,formvalue){if(!uci.get('system','ntp')){uci.add('system','timeserver','ntp');}
var servers=[];if(formvalue!==undefined&&formvalue!==null){servers=Array.isArray(formvalue)?formvalue:[formvalue];servers=servers.filter((item,index,self)=>{return item&&self.indexOf(item)===index;});}
if(servers.length>0){uci.set('system','ntp','server',servers);}else{uci.remove('system','ntp');uci.add('system','timeserver','ntp');uci.set('system','ntp','enabled','1');uci.set('system','ntp','enable_server','0');}};o.render=function(option,section_id,input){return Promise.all([form.DynamicList.prototype.render.apply(this,arguments),this.load(section_id)]).then(function(results){var container=results[0];var servers=results[1]||[];var addContainer=container.querySelector('.cbi-dynlist .add-item');if(addContainer){addContainer.style.display=servers.length>=4?'none':'';var observer=new MutationObserver(function(){var currentItems=container.querySelectorAll('.cbi-dynlist .item');addContainer.style.display=currentItems.length>=4?'none':'';});observer.observe(container.querySelector('.cbi-dynlist'),{childList:true,subtree:true});container._dynlistObserver=observer;}
return container;});};o.remove=function(section_id,formvalue){var container=document.getElementById(this.cbid(section_id));if(container&&container._dynlistObserver){container._dynlistObserver.disconnect();}
this.write(section_id,formvalue);return form.DynamicList.prototype.remove.apply(this,arguments);};}
return m.render().then(function(mapEl){poll.add(function(){return callGetLocaltime().then(function(t){var el=mapEl.querySelector('#localtime');if(el)
el.value=formatTime(t);});});return mapEl;});}});