'use strict';'require view';'require dom';'require poll';'require fs';'require ui';'require uci';'require form';'require network';return view.extend({load:function(){return uci.load('network');},render:function(){let dsliteSections=uci.get('network','dslite')||{}
let dslieMap={'dslite':dsliteSections}
var m=new form.JSONMap(dslieMap,_('DSLite Connection'),_('This page provides the function of WAN connection parameter(s) configuration.'));var s=m.section(form.TypedSection,'dslite');s.anonymous=true;const enabled=s.option(form.ListValue,'defaultroute',_('Enable'));enabled.widget='radio';enabled.value('1',_('On'));enabled.value('0',_('Off'));enabled.datatype='integer';enabled.default='1';enabled.modalonly=true;var o=s.option(form.Value,'_name',_('Connection Name'),_('Please enter a value with 1 ~ 10 characters.'));o.optional=false;o.rmempty=false;o.modalonly=true;o.datatype='maxlength(10)'
var tunLink=s.option(form.ListValue,'tunlink',_('WAN Connection'));tunLink.value('wan6',_('WAN'));tunLink.modalonly=true;var ipv4Address=s.option(form.Value,"ipaddress",_("Interface IPV4 Address"));ipv4Address.default="192.0.0.2"
ipv4Address.readonly=true
var peerAddr=s.option(form.Value,'peeraddr',_('AFTR'),_('Please enter a value with 1 ~ 256 characters.'));peerAddr.optional=false;peerAddr.datatype='maxlength(256)';peerAddr.modalonly=true;peerAddr.placeholder=_('Enter peerAddr (1-256 characters)');peerAddr.validate=function(section_id,value){if(!value.match(/^[\x00-\x7F]+$/)){return _("Only English letters, numbers and symbols are allowed");}
return true;};var super_save=m.save
m.save=function(){return super_save.apply(this,arguments).then(function(){if(!uci.get('network','dslite')){uci.add('network','interface','dslite');}
var connectioNname=s.children.find(opt=>opt.option==='_name')?.formvalue('dslite')||'';var wanConnection=s.children.find(opt=>opt.option==='tunlink')?.formvalue('dslite')||'';var aftr=s.children.find(opt=>opt.option==='peeraddr')?.formvalue('dslite')||'';var defaultroute=s.children.find(opt=>opt.option==='defaultroute')?.formvalue('dslite')||'';uci.set('network','dslite','defaultroute',defaultroute);uci.set('network','dslite','_name',connectioNname);uci.set('network','dslite','tunlink',wanConnection);uci.set('network','dslite','depends',wanConnection);uci.set('network','dslite','peeraddr',aftr);uci.set('network','dslite','proto','dslite')
return uci.save().then(function(){return true;});})}
return m.render();}});