'use strict';'require view';'require rpc';'require ui';'require dom';'require fs';const ethToLan={'eth0':'LAN1','eth1':'LAN2','eth2':'LAN3','eth3':'LAN4',}
return view.extend({callGetPageLoad:rpc.declare({object:'luci',method:'usecmapi',params:['method','data'],expect:{}}),expandIPv6:function(ipv6){if(!ipv6||ipv6==='')return'';ipv6=ipv6.split('%')[0];var parts=ipv6.split('::');var leftParts=parts[0]?parts[0].split(':'):[];var rightParts=parts[1]?parts[1].split(':'):[];var totalParts=leftParts.length+rightParts.length;var missingParts=8-totalParts;var fullParts=leftParts.slice();for(var i=0;i<missingParts;i++){fullParts.push('0');}
fullParts=fullParts.concat(rightParts);var expandedParts=fullParts.map(function(part){return('0000'+part).slice(-4);});return expandedParts.join(':');},load:function(){return this.callGetPageLoad('webagent_access_dev_get','{}').then(response=>{var lanClientData=JSON.parse(response.data||'[]');var self=this;var natPromises=lanClientData.map(function(client){var hasIPv4=client.IPAddress&&client.IPAddress!=='';var hasIPv6=client.IPV6Address&&client.IPV6Address!=='';if(!hasIPv4&&!hasIPv6){client.NATEntries='0';return Promise.resolve(client);}
var promises=[];if(hasIPv4){promises.push(fs.exec('/bin/grep',['-c','src='+client.IPAddress,'/proc/net/nf_conntrack']).then(function(result){return parseInt((result.stdout||'0').trim(),10);}).catch(function(){return 0;}));}else{promises.push(Promise.resolve(0));}
if(hasIPv6){var expandedIPv6=self.expandIPv6(client.IPV6Address);if(expandedIPv6){promises.push(fs.exec('/bin/grep',['-c','src='+expandedIPv6,'/proc/net/nf_conntrack']).then(function(result){return parseInt((result.stdout||'0').trim(),10);}).catch(function(){return 0;}));}else{promises.push(Promise.resolve(0));}}else{promises.push(Promise.resolve(0));}
return Promise.all(promises).then(function(counts){client.NATEntries=String(counts[0]+counts[1]);return client;});});return Promise.all(natPromises).then(clients=>[{data:JSON.stringify(clients)}]);});},render:function(data){var lanClientData=JSON.parse(data[0].data||'[]');var container=E('div');container.appendChild(E('h3',{'name':'content'},_('LAN Client Status')));lanClientData.forEach(function(Data,index){if(Data.AliasName.indexOf('eth')<0)
return
var arr=this.dataToArr(Data);var lanClientTable=E('table',{'class':'table'});lanClientTable.appendChild(E('tr',{'class':'tr colorTblRow emFont titleRow'},[E('td',{'class':'td left emFont','width':'130px'},_('Client- %s').format(index+1)),E('td',{'class':'td left','width':'180px'},''),E('td',{'class':'td left emFont','width':'200px'},''),E('td',{'class':'td left','width':'150px'},''),]));var rowNum=0;for(var i=0;i<arr.length;i+=2)
{var classStr=rowNum%2==0?"tr colorTblRow":"tr colorTblRow colorRow";lanClientTable.appendChild(E('tr',{'class':classStr},[E('td',{'class':'td left emFont','width':'130px'},arr[i][0]),E('td',{'class':'td left','width':'180px'},arr[i][1]),E('td',{'class':'td left emFont','width':'200px'},arr[i+1]!=undefined?arr[i+1][0]:""),E('td',{'class':'td left','width':'150px'},arr[i+1]!=undefined?arr[i+1][1]:""),]));rowNum++;}
container.appendChild(lanClientTable);}.bind(this));container.appendChild(E('div',{'style':'text-align: right; margin-top: 20px'},E('button',{'class':'btn cbi-button refreshBtn','style':'min-width: 100px','click':ui.createHandlerFn(this,function(){window.location.reload();})},_('Refresh'))));return container;},handleSaveApply:null,handleSave:null,handleSaveInst:null,handleReset:null,dataToArr:function(data){var arr=[];arr.push([_('Port'),ethToLan[data["AliasName"].toLowerCase()]]);arr.push([_('Name'),data["HostName"]]);arr.push([_('IPV4Address'),data["IPAddress"]]);arr.push([_('MACAddress'),data["MACAddress"]]);arr.push([_('IPV6Address'),data["IPV6Address"]]);arr.push([_('NAT entries/conntracks'),data["NATEntries"]||'0']);return arr;},});